name: PloudStorePlugin
version: '${project.version}'
main: org.ploudstore.ploudStorePlugin.PloudStorePlugin
load: POSTWORLD
description: PloudStore payment processor plugin
authors: [PloudStore]

commands:
  ploudstore:
    description: PloudStore commands
    usage: /ploudstore <pin|secret|reload|status|forcecheck|help>
    aliases: [ps]

permissions:
  ploudstore.admin:
    description: Acesso aos comandos de administração do PloudStore
    default: op
  ploudstore.player:
    description: Acesso ao comando /ploudstore pin
    default: true
